language: node_js
node_js:
- '5'
services:
- postgresql
env:
- DB=postgresql
before_script:
- psql -c 'create database app;' -U postgres
deploy:
  api_key:
    provider: heroku
    secure: BQn91iMZzI/7YuNLRrUnBXlIM+GHFDCMp4EzCTuhRLioYsoPY8MMIri0w0KmYN4qlB/08z2pXI0l61MrYt48/2S17Wv/N9NiCL31T2dd/7GF18dKZ/a50TpQLM+VxvRftM1qFYvIQhIQUSrLKwqQT5CSReKZNqxtDOWfkYKRrI0R6RwuZ+dpj4DTK7ta3TQaMQ+e5FF9EL19fQXChs3wk/+1jGGqWH2CsZXb/qI2i3ruac4rKTJ76aYyjRVy8tXS83O3+rOYwsIJ3h6JHfJ8r4BFBP6rP+QK1iw84Sswl3+3uZvYRBR2HiKB+wHtdn3Y3nkfB5dNNg9pr7mnH/Od+m4iCyFc+XdD/mwwB0R5+Eqii3JO2raEBpBszk+Po3uwpiM8WGgzjnBPfZq1Nahh79AGn09TyyGqAXZV/61mk+BITtbZsbxTAEAsJkudF7HhfziXky9o929+vPRsFdppeICO7TeEO4teR6PThaWV6V1kWglG8OTsCU0NumR3HYAB/cxaWlTrZ/LjcatMMHlmK2sQRNKCRhaT1FrzSNldCC2iEZDVWxXKvqgzpTTfyOqI74eOtjruhhoIsZUlBYZCUFeVtK3SY815hobFcCK6QbG3mYACRijpi8zpX8igxqquoqRjFyL0ZTApO/4sXOSVaNv4yidFuJNGvwLixI+0ZJo=
