#TODO Better config here
language: node_js
node_js:
	 - "5"
services: 
	- postgresql
env: 
	- DB=postgresql
before_script:
	- psql -c 'create database app;' -U postgres
	- psql -c 'alter user "postgres" with password "password"' -U postgres