language: node_js
node_js:
- '5'
services:
- postgresql
env:
- DB=postgresql
before_script:
- psql -c 'create database app;' -U postgres
deploy:
  api_key:
    provider: heroku
    secure: fA23eDZj7cYsUw025sFM37Dc2bPNgAoz6WxY+gwN2IF9gDT1gLHBRFH/LeRpvcu/10e7PxGYhrmiJG+n+lBOTr38I0sn5yKyK2q4MfjbQqPF5HELgjM1co1SRKz0jHOpzsol9fw/HLmIq1PTaeWJzckncHqytuI2og1WildYZIhkWqpHRshkQHTU2ASBkbR7fzYvjUoAL3+4lRjwh0iDRB0Kc+qtrPtt31nXJcxKLtDGRd97NL7VPbeRsmlLlsCP4kCzo1ulxVp2hSWjLNDSVLmCKYHhzRcuMiEgxj9WhpcDLVOmMmPkjp3vDI/NXOPcjUGGHinUgpB/ac+lqakTKrakXZxAOntfm5trJGlLAH1LiD1iQ0De0D+aEhW2S2qdFgN2fy+vU0PL1tzqPlLiZqZpPzXVB+4NAByl+hSFxh4fE1y1RGsef32EN2BpVU1DLxsHbIPztHloeMZr03KOM7KtToEuZWYc8KczpnmZEUr72R+U5ef6H4XE0mfBnJEVvzyXrZ4XtFLtljCPi12e2oNsLlIs8luRUU9iHld3WWJV4eYrESgPdEfDGbo5HPBG49/1EbiECLdqU7Prfo5sToo+3AD1YrFG1ZuWMpyWwJu4iYIRPZV93dNzr0omQTeqixyVxGiSF6UldeCWn1DL0Q2OZgtpmAjAhXZOJS5ybgI=
